### ISSUE TITLE
How to temperally stop proxydetox

### ISSUE THREAD

**Issue by leona0918** [kiron1/proxydetox#191]
proxydetox version: 0.5.3
OS : macOS Monterey , 12.4

I could stop proxydetox by 
`launchctl kill SIGTERM gui/$(id -u)/cc.colorto.proxydetox`
But it atuto start again ,even if after command 
`launchctl disable gui/$(id -u)/cc.colorto.proxydetox`

So what's the correct way to temperally stop proxydetox?

**Comment by kiron1** [comment]
`cc.colorto.proxydetox` is activated by sockets and not started as a daemon (see the [launch plist file](https://github.com/kiron1/proxydetox/blob/main/pkg/macos/cc.colorto.proxydetox.plist#L17-L32)). This means, the process of proxydetox is started on demand as soon as some application needs to use it (by connecting to port tcp/3128 on localhost) which is the preferred way to start daemons on macOS.

Assuming that there are still applications running which are configured to use the proxy, would explain why proxydetox start again after you killed it.

Either make sure that you disable all tools from using a proxy, then proxydetox will remain stopped, or completely remove the proxydetox from launchd via:

```sh
launchctl bootout gui/$(id -u)/cc.colorto.proxydetox
```

and to re-enable use:

```sh
launchctl bootstrap gui/$(id -u) /Library/LaunchAgents/cc.colorto.proxydetox.plist
```
