### ISSUE TITLE
Error 502 Bad request with version 0.7.1

### ISSUE THREAD

**Issue by smirko-dev** [kiron1/proxydetox#311]
With version 0.7.1 proxydetox can't reach external webpages while using VPN.
`curl -iL http://example.org` returns Error 502 Bad request.
After downgrading to version 0.6.4 it works.

MacBook Pro M2 Max
macOS: Ventura 13.5

**Comment by kiron1** [comment]
Hello @smirko-dev

can you provide more details to better support.

- How did you build/install proxydetox?
- How are you running proxydetox?
- You can use the `-v` flag to make proxydetox more verbose, such that we can see what is internally happening.
- How does the PAC file look like and how do you authenticate against the proxy?
- What vpn?
- what’s the output of the command: `curl -ivL http://example.org`

**Comment by smirko-dev** [comment]
I installed proxydetox and followed the instructions from here: https://proxydetox.colorto.cc/book/installation.html#macos.
For VPN I use AnyClient from Cisco.
Further details I can't give you, since I don't wanna touch a running system now ^^.
Curl output:
```
HTTP/1.1 502 Bad Gateway
content-type: text/html
connection: close
content-length: 510
date: Fri, 01 Sep 2023 04:23:27 GMT

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Internal Server Error 502</title>
<style type="text/css"><!--
body { background: #a00000; color: white; font-family: 'Comic Sans MS', 'Chalkboard SE', 'Comic Neue', sans-serif; }
hr { border: 0; border-bottom: 1px dashed; }
--></style>
</head>
<body>
<h1>Internal Server Error 502</h1>
<div><p><strong>Error:</strong> unable to establish connection: http://example.org/</p></div>
<hr>
<address>proxydetoxlib/0.6.4</address>
</body>
</html>
```

**Comment by smirko-dev** [comment]
Thanks a lot :)

**Comment by imyumichan** [comment]
Hi @kiron1,  I got the same issue on 0.8.3 and the latest version 0.9.5. It seems that the issue hasn't resolved fully yet.

**Comment by kiron1** [comment]
@imyumichan an error 502 can have many reasons. Please provide more information to reproduce this error and open a new issue.

**Comment by kiron1** [comment]
@imyumichan when you PAC file was using `myIpAddress` then the issue is fixed with https://github.com/kiron1/proxydetox/pull/431 in version 0.9.6.

Otherwise please open a proper issue with proper description on how to reproduce.
