### ISSUE TITLE
Always need restart if there is no krb5 ticket

### ISSUE THREAD

**Issue by Alchantness** [kiron1/proxydetox#356]
Hello! Nice work, like it. There is an issue:
While there is no valid krb5ccache ticket, proxy will not work, obviously. When i get new ticket, for example, with kinit command, i need to manually restart proxydetox service. Is there a way to learn search for ticket dinamically? Thanks!
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
Latest version of proxydetox.

**Comment by kiron1** [comment]
I don’t have this problem. Maybe your systems Kerberos integration/configuration is not complete.
