### ISSUE TITLE
Can't load PAC on 0.8.0

### ISSUE THREAD

**Issue by hashiz** [kiron1/proxydetox#392]
Version 0.8.0 can't load PAC file on my environment.
Version 0.7.8 are work fine.

It's suddenly terminated during PAC downloading.

The PAC file size is 33774 bytes.

capture download stream:
-----------------------------------------------------------------------
GET /xxxx-yyy.com/xxxx_j_proxy.pac HTTP/1.1
Host: pac.zscloud.net
Connection: close

HTTP/1.1 200 OK
Content-type: application/x-ns-proxy-autoconfig
Connection: close

//
//Office 365 Proxy Automatic Configuration File
//built from Office 365 Automatic Proxy PAC File Creator
//
//Author: aaron.guilmette@microsoft.com
//Link: https://gallery.technet.microsoft.com/Office-365-Proxy-Pac-60fb28f7
//Modify: hideto.tange@toyo-eng.com
//
//This file is genarated based on the version of 2024053000.
//
function FindProxyForURL(url, host) {
    var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
    var resolved_ip = dnsResolve(host);
    var egressip = "103.175.36.131";

    /* Don't send non-FQDN or private IP and akamaiEEA auths to us */
    if (isPlainHostName(host) || isInNet(resolved_ip, "192.0.2.0","255.255.255.0") || isInNet(resolved_ip,"100.64.0.0","255.192.0.0") || privateIP.test(resolved_ip))
        return "DIRECT";

~~~
snip
~~~
        dnsDomainIs(host, "login.windows.net")||
        dnsDomainIs(host, "login.microsoftonline.com")||
        dnsDomainIs(host, "login.live.com")||
        dnsDomainIs(host, "secure.aa
-----------------------------------------------------------------------
terminated suddenly.

**Comment by kiron1** [comment]
Is the problem that the PAC file cannot be downloaded, or it cannot be parsed?

not sure where this “capture download stream” comes from. Is this out put of Proxydetox or a `curl` call which succeeds, but Proxydetox fails?

**Comment by hashiz** [comment]
This is a download issue, I think.

The capture is a network packet capture with wireshark.
It seems suddenly terminated during downloading.

Yes, only proxydetox has this problem.
Another tools such as "wget" can download it successfully.

**Comment by kiron1** [comment]
Difficult to analyze this without more qualified information.
A wireshark trace usually contains more information than shown above. Additionally debug output of Proxydetox, the error message on the server side, as well as a verbose output of `curl -v …` (but not `wget`, since it tries to auto resume failed downloads) would be useful.

**Comment by hashiz** [comment]
@kiron1 
I can provide more detailed information.
But I don't want to expose it to the public.
Do you have any good idea?

error message:
$ systemctl --user status proxydetox.service | cat
● proxydetox.service - Proxydetox Daemon
     Loaded: loaded (/usr/lib/systemd/user/proxydetox.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-08-06 11:18:15 JST; 9s ago
       Docs: https://proxydetox.colorto.cc/
   Main PID: 889 (proxydetox)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/proxydetox.service
             └─889 /usr/bin/proxydetox

Aug 06 11:18:15 TJ-PW03S0XS systemd[519]: Started proxydetox.service - Proxydetox Daemon.
Aug 06 11:18:15 TJ-PW03S0XS proxydetox[889]:    0.002091053s  INFO proxydetox: starting listening=[127.0.0.1:8080] pac_file=Some(Uri(http://pac.zscloud.net/xxxx-yyy.com/xxxx_j_proxy.pac))
Aug 06 11:18:15 TJ-PW03S0XS proxydetox[889]:    0.002113226s  INFO load_pac_file: proxydetoxlib::context: update PAC script uri=Some(Uri(http://pac.zscloud.net/xxxx-yyy.com/xxxx_j_proxy.pac))
Aug 06 11:18:15 TJ-PW03S0XS proxydetox[889]:    0.475050548s ERROR proxydetoxlib::context::builder: failed to load PAC from URI cause=Unknown size pac_file=Some(Uri(http://pac.zscloud.net/xxxx-yyy.com/xxxx_j_proxy.pac))

**Comment by kiron1** [comment]
The issue could be that currently we reject the download of PAC files when the HTTP server does not report the file size vie `Content-Length`. Can you confirm this header is missing (it looks like such from your incomplete trace).

(Please ensure to use the markdown formatting options from GitHub comments correctly to make reading your submissions easier).

**Comment by hashiz** [comment]
@kiron1 I have been able to download the pac with v0.8.1. Thanks.
